version: '3.8'

services:
  stats-db:
    image: postgres:16.1-alpine
    container_name: stats-db
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d stats"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  stats-server:
    build:
      context: .
      dockerfile: stats/stats-server/Dockerfile
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 9090
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"

  ewm-service:
    build:
      context: .
      dockerfile: ewm-service/Dockerfile
    container_name: ewm-service
    environment:
      STATS_SERVER_URL: http://stats-server:9090
      SERVER_PORT: 8083
    depends_on:
      - stats-server
    ports:
      - "8083:8083"

volumes:
  stats-db-data:a: