# Main service
server.port=8080
  
  # Stats service URL - ВАЖНО!
stats.service.url=http://localhost:9090
  
  # H2 Database
spring.datasource.url=jdbc:h2:file:./db/maindb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
  
  # JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
  
  # Logging
logging.level.ru.practicum.explorewithme=DEBUG
logging.level.org.springframework.web=DEBUG